### ISSUE TITLE
Request throws 422 on not required attribute

### ISSUE THREAD

**Issue by acrontum-sanchez** [acr-lfr/generate-it-typescript-server#162]
I have a route with the following model:

```
type: object
required:
  - generalProfile
  - addWorkAddressToProfile
properties:
  generalProfile:
    $ref: '../index.yml#/Profile'
  work:
    $ref: '../index.yml#/Work'
  study:
    $ref: '../index.yml#/Study'
  addWorkAddressToProfile:
    type: boolean

```
Based on this model study or work are not required but I still get a 422 

```
"details": [
      {
        "message": "\"work\" is required",
        "path": [
          "work"
        ],
        "type": "any.required",
        "context": {
          "label": "work",
          "key": "work"
        }
      }
    ]
```
The work model is defined like :

```
type: object
required:
  - pharmacyId
  - startDate
properties:
  _id:
    type: string
  profileId:
    type: string
  pharmacyId:
    type: string
  pharmacy:
    $ref: '../index.yml#/Pharmacy'
  startDate:
    type: string
    format: date
  endDate:
    type: string
    format: date
```

When I add the work into the request `"work": {},` I get the following 422 ` "message": "\"work.pharmacy\" is required",`.
