### ISSUE TITLE
multipart/form-data validations not working

### ISSUE THREAD

**Issue by acrontum-sanchez** [acr-lfr/generate-it-typescript-server#163]
When sending a multipart form (file + some attribute) the generated joi validations are empty making the request to fail always.

**Request model**

```
type: object
properties:
  studentCard:
    type: string
    format: binary
  studentCardIssuedAt:
    type: string
    format: date
  studentCardPlaceOfIssue:
    type: string
```

**Generated validations:**

```
  verificationStep2Post: {
    body: Joi.object({}),
  },
 ```
 
 ** API result **
 
 ```
 "details": [
      {
        "message": "\"studentCardIssuedAt\" is not allowed",
        "path": [
          "studentCardIssuedAt"
        ],
        "type": "object.unknown",
        "context": {
          "child": "studentCardIssuedAt",
          "label": "studentCardIssuedAt",
          "value": "2018-01-12",
          "key": "studentCardIssuedAt"
        }
      }
    ]
```
 
 Generate it version: 5.33.0
