### ISSUE TITLE
[FEAT]: Choose if required field referenced in .yml will be null or not

### ISSUE THREAD

**Issue by lucas-paim-acrontum** [acr-lfr/generate-it-typescript-server#185]
Generate it is allowing required fields from referenced models to be null. In order to avoid creating a duplicate model to enforce the already described rules, would be nice if we could control this behavior.

---
Example:
`Address Model`
```yml
type: object
required:
  - street
  - houseNumber
properties:
  _id:
    type: string
  street:
    type: string
    minLength: 3
    maxLength: 100
  houseNumber:
    type: string
    minLength: 1
    maxLength: 10
  isDefault:
    type: boolean
    default: false

```
---
`Pharmacy Model`
```yml
type: object
required:
  - name
  - address
properties:
  address:
    $ref: '@/components/schemas/address/model.yml'
  name:
    type: string
    minLength: 3
    maxLength: 100

```
---
This will produce the following validator:
```typescript
import { Joi } from 'celebrate';

export default {
  pharmacyGet: {
    query: Joi.object({
      pharmacyName: Joi.string().min(3).max(100).required(),
    }),
  },

  pharmacyPost: {
    body: Joi.object({
      address: Joi.object({
        _id: Joi.string().allow('').allow(null),
        street: Joi.string().min(3).max(100).allow(null),
        houseNumber: Joi.string().min(1).max(10).allow(null),
        isDefault: Joi.boolean().allow(null),
      }).required(),
      name: Joi.string().min(3).max(100).required(),
    }),
  },
};

```

Street and 'houseNumber' should not be allowed as null since they are required in the Address Model.
