### ISSUE TITLE
BUG: fix docker-compose again

### ISSUE THREAD

**Issue by p-mcgowan** [acr-lfr/generate-it-typescript-server#50]
Not sure if this is the place to put it, but the image name and networks need updating

```yaml
{%- set serviceName =  _.kebabCase(package.name) | replace(r/[-_]*swagger$/, "") -%}
version: "3"

# virtual volume
volumes:
  build:

services:
  {{ serviceName }}:
    image: "${IMAGE_PREFIX}{{ serviceName }}:${IMAGE_TAG:-latest}"
    build: # this stuff isnt necessary but could keep it just for clarity
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - build:/code/build
      - ./global.d.ts:/code/global.d.ts
      - ./server.ts:/code/server.ts
      - ./tsconfig.json:/code/tsconfig.json
      - ./src:/code/src/
    ports:
      - "8080:8000"
    # networks:
    #   - backend-network
    #   - postgres-network
    working_dir: /code
    entrypoint: /bin/sh
    command: '-c "npx tsc-watch --preserveWatchOutput --compiler /code/node_modules/.bin/ttsc --onSuccess "/sbin/docker-entrypoint.sh prod""'

# networks:
#   backend-network:
#     external:
#       name: "backend-network"
#   postgres-network:
#     external:
#       name: "postgres-network"
```
